name: Validate & Release Chart

on:
  push:
    branches:
      - '**'

env:
  OPENSHIFT_SERVER: "https://api.sandbox.x8i5.p1.openshiftapps.com:6443"
  OPENSHIFT_NAMESPACE: "aernouthoebreckx-dev"
  HELM_RELEASE_NAME: "tafun-helm"
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        run: helm lint .
  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Helm upgrade
        run: |
          helm package .
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} .