name: Validate & Release Chart

on:
  push:
    branches:
      - '**'

env:
  OPENSHIFT_SERVER: "https://api.sandbox.x8i5.p1.openshiftapps.com:6443"
  OPENSHIFT_NAMESPACE: "aernouthoebreckx-dev"
  HELM_RELEASE_NAME: "tafun-helm"
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        run: helm lint charts/tafun-quarkus/
      - name: git-get-release-action
        id: gitRelease
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          latest: true
      - name: Check output
        run: |
          echo "${{ steps.gitRelease.outputs.name }}"
          echo "${{ steps.gitRelease.outputs.assets }}"
          echo "${{ steps.gitRelease.outputs.assets.[0] }}"
  release:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  deploy-dev:
    needs: release
    if: github.ref == 'refs/heads/main'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Helm upgrade
        run: |
          helm package .
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} .